name: Deploy Pelican Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.6'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt

    - name: Build Pelican Site
      run: pelican content -s pelica

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs  # Pelican 输出目录
        publish_branch: gh-pages  # 明确指定目标分支
        force_orphan: true  # 强制清空 gh-pages 分支历史（仅保留最新内容）
