name: Deploy Pelican Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.6'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pelican ghp-import markdown

    - name: Build Pelican Site
      run: pelican content

    - name: Deploy to GitHub Pages
      run: |
        ghp-import docs -b gh-pages
        git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
